build:
	cd ckb && docker build -t tockb/ckb-dev:v0.39.2 .
	cd ckb-indexer && docker build -t tockb/ckb-indexer .
	cd geth && docker build -t tockb/geth-priv:v1.9.23 .
	cd bitcoin && docker build -t tockb/btc-regtest .
	cd eos && docker build -t tockb/eosio-priv:2.0.11 .
