build:
	cd ckb && docker build -t tockb/ckb-dev:v0.100.0 .
	cd ckb-indexer && docker build -t tockb/ckb-indexer:v0.3.0 .
	cd geth && docker build -t tockb/geth-priv:v1.10.10 .
	cd bitcoin && docker build -t tockb/btc-regtest .
	cd eos && docker build -t tockb/eosio-priv:2.0.11 .
